### PR TITLE
removed ANT ifdefs for Android Studio compatibility

### PR DESCRIPTION
**Pull request by frankmorgner**
I've integrated PivApplet into a [contactless smart card emulator on Android](http://frankmorgner.github.io/vsmartcard/ACardEmulator/README.html). Basically, I've tied the code to a speciffic configuration, because Android studio doesn't understand ant's ifdefs, afaik. Please comment if you see a better way for integrating the code...

### CODE REVIEW

**Comment by frankmorgner** [comment]
https://github.com/frankmorgner/vsmartcard/commit/75779ea77a27a759126ed6e0ec73f300678961a2

**Comment by arekinath** [comment]
In ecfc3389a078877fe418f6f8e7fa7332fcdbeb0e I've changed it over to use the comment forms of the preprocessor directives, so that to something unaware of them they now see just the default state of the toggle (since the other option is behind a comment).

**Comment by frankmorgner** [comment]
that could work...

**Comment by arekinath** [comment]
I think I would rather make the comments thing work than add preprocessed code to the repo itself. If I've messed up the comments anywhere and they need fixing for what you want to do, let me know -- I'm also happy to take a PR that surrounds some bits with `//#if EMULATOR` or `/*#if !EMULATOR` to make it look the way you need it to as long as it doesn't end up absolutely everywhere. :)

**Pull request closed without merging**
